I am Dhyan Roopesh and a teenage Dev(13)...
This is my first ever game and wanna make it a public source,You can modify this and uss.
Very Well this project was also a collabration with other user and youtube Mr.Nick
* Youtube : https://www.youtube.com/@programmingwithnick
* Github : https://github.com/educ8s/Raylib-CPP-Starter-Template-for-VSCODE/commits?author=educ8s
........................................................
You can Download this Zip file and click the .exe fie to access the game...
I have aldready Uploaded Game In Itch.io
You Can checkout it through my Itch.io
........................................................
I Will Be Uploading The source code of this game in next repository
And If You Wanna SUPPORT ME For My Next Projects You can Send Donations Through
* Buy Me A Coffee : https://buymeacoffee.com/Vara_Pixel
If You can Support Me please Support through the platform
........................................................
THIS GAME IS MADE WITH RAYLIB
........................................................
